# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: downloads/test.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'downloads/test.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64ownloads/test.proto\"\'\n\tOperation\x12\x0c\n\x04num1\x18\x01 \x01(\x01\x12\x0c\n\x04num2\x18\x02 \x01(\x01\"\x18\n\x06Result\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32I\n\nCalculator\x12\x1a\n\x03\x41\x64\x64\x12\n.Operation\x1a\x07.Result\x12\x1f\n\x08Subtract\x12\n.Operation\x1a\x07.Resultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'downloads.test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERATION']._serialized_start=24
  _globals['_OPERATION']._serialized_end=63
  _globals['_RESULT']._serialized_start=65
  _globals['_RESULT']._serialized_end=89
  _globals['_CALCULATOR']._serialized_start=91
  _globals['_CALCULATOR']._serialized_end=164
# @@protoc_insertion_point(module_scope)
